package gui;

import controller.Controller;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class FinestraInserisciUtente {
    private JPanel panelInserisciUtente;
    private JButton registrazioneButton;
    private JTextField usernameInseritoTextField;
    private JPasswordField passwordInseritaField;
    private JPanel panelInserisciUsername;
    private JPanel panelInseritoPasssword;
    private JPanel panelButtonInseritiValori;
    private static JFrame frameChiamante;
    private static JFrame frame;
    private Controller controller;
    private String usernameInserito;
    private String passwordInserita;

    public FinestraInserisciUtente(JFrame frameChiamante, Controller controller) {
        this.frameChiamante = frameChiamante;
        this.controller = controller;
        frame = new JFrame("Registrazione Utente");
        frame.setContentPane(panelInserisciUtente);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        usernameInseritoTextField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });

        passwordInseritaField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        registrazioneButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                usernameInserito = usernameInseritoTextField.getText();
                char[] passwordChars = passwordInseritaField.getPassword();  // per ottenere la password
                passwordInserita = new String(passwordChars);
 //               try {
   //                 if (!(usernameInserito.isEmpty() || passwordInserita.isEmpty())) {
                        controller.setUtente(usernameInserito, passwordInserita);
     //               }
       //         } catch (invalidLoginException il) {
         //           throw new RuntimeException(il);
           //     }
                JOptionPane.showMessageDialog(frame, "Ciao " + usernameInserito + " Benvenuto nel nostro sistema");
                frameChiamante.setVisible(true);
                frame.setVisible(false);
                frame.dispose();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelInserisciUtente = new JPanel();
        panelInserisciUtente.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelInserisciUsername = new JPanel();
        panelInserisciUsername.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelInserisciUsername.setPreferredSize(new Dimension(88, 40));
        panelInserisciUtente.add(panelInserisciUsername);
        usernameInseritoTextField = new JTextField();
        usernameInseritoTextField.setPreferredSize(new Dimension(78, 30));
        usernameInseritoTextField.setText("");
        panelInserisciUsername.add(usernameInseritoTextField);
        panelInseritoPasssword = new JPanel();
        panelInseritoPasssword.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelInseritoPasssword.setPreferredSize(new Dimension(88, 40));
        panelInserisciUtente.add(panelInseritoPasssword);
        passwordInseritaField = new JPasswordField();
        passwordInseritaField.setPreferredSize(new Dimension(78, 30));
        panelInseritoPasssword.add(passwordInseritaField);
        panelButtonInseritiValori = new JPanel();
        panelButtonInseritiValori.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelInserisciUtente.add(panelButtonInseritiValori);
        registrazioneButton = new JButton();
        registrazioneButton.setText("Registrati");
        panelButtonInseritiValori.add(registrazioneButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelInserisciUtente;
    }

}
