package gui;

import controller.Controller;
import controller.LunghezzaPasswordException;
import controller.invalidLoginException;
import controller.GiaEsistenteException;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class FinestraInserisciUtente {
    private JPanel panelInserisciUtente;
    private JButton registrazioneButton;
    private JTextField usernameInseritoTextField;
    private JPasswordField passwordInseritaField;
    private JPanel panelInserisciUsername;
    private JPanel panelInseritoPasssword;
    private JPanel panelButtonInseritiValori;
    private JButton annullaButton;
    private static JFrame frameChiamante;
    private static JFrame frame;
    private Controller controller;
    private String usernameInserito;
    private String passwordInserita;

    public FinestraInserisciUtente(JFrame frameChiamante, Controller controller) {
        this.frameChiamante = frameChiamante;
        this.controller = controller;
        frame = new JFrame("Registrazione Utente");
        frame.setContentPane(panelInserisciUtente);
        frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); // Evita la chiusura automatica
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Logica quando la finestra di inserimento autore sta chiudendo
                frameChiamante.setVisible(true);
                frame.dispose(); // Chiude la finestra di inserimento autore
            }
        });
        frame.pack();
        frameChiamante.setVisible(false);
        frame.setVisible(true);
        usernameInseritoTextField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });

        passwordInseritaField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        registrazioneButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                usernameInserito = usernameInseritoTextField.getText();
                char[] passwordChars = passwordInseritaField.getPassword();  // per ottenere la password
                passwordInserita = new String(passwordChars);
                try {
                    controller.setUtente(usernameInserito, passwordInserita);
                    JOptionPane.showMessageDialog(frame, "Ciao " + usernameInserito + " benvenuto nel nostro sistema");
                    frameChiamante.setVisible(true);
                    frame.setVisible(false);
                    frame.dispose();
                } catch (invalidLoginException il) {
                    JOptionPane.showMessageDialog(frame, "Non puoi lasciare un campo vuoto.");
                } catch (GiaEsistenteException ex) {
                    JOptionPane.showMessageDialog(frame, "L'username inserito è già esistente");
                } catch (LunghezzaPasswordException ex) {
                    JOptionPane.showMessageDialog(frame, "La password deve essere lunga almeno 6 caratteri");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(frame, "Errore generico");
                }
            }
        });
        annullaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frameChiamante.setVisible(true);
                frame.setVisible(false);
                frame.dispose();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelInserisciUtente = new JPanel();
        panelInserisciUtente.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelInserisciUsername = new JPanel();
        panelInserisciUsername.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelInserisciUsername.setPreferredSize(new Dimension(88, 40));
        panelInserisciUtente.add(panelInserisciUsername);
        usernameInseritoTextField = new JTextField();
        usernameInseritoTextField.setPreferredSize(new Dimension(78, 30));
        usernameInseritoTextField.setText("");
        panelInserisciUsername.add(usernameInseritoTextField);
        panelInseritoPasssword = new JPanel();
        panelInseritoPasssword.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelInseritoPasssword.setPreferredSize(new Dimension(88, 40));
        panelInserisciUtente.add(panelInseritoPasssword);
        passwordInseritaField = new JPasswordField();
        passwordInseritaField.setPreferredSize(new Dimension(78, 30));
        panelInseritoPasssword.add(passwordInseritaField);
        panelButtonInseritiValori = new JPanel();
        panelButtonInseritiValori.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelInserisciUtente.add(panelButtonInseritiValori);
        registrazioneButton = new JButton();
        registrazioneButton.setText("Registrati");
        panelButtonInseritiValori.add(registrazioneButton);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.setPreferredSize(new Dimension(102, 40));
        panelInserisciUtente.add(panel1);
        annullaButton = new JButton();
        annullaButton.setMaximumSize(new Dimension(92, 30));
        annullaButton.setMinimumSize(new Dimension(92, 30));
        annullaButton.setPreferredSize(new Dimension(92, 30));
        annullaButton.setText("Annulla");
        panel1.add(annullaButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelInserisciUtente;
    }

}
