package gui;

import controller.Controller;
import model.Autore;
import model.Utente;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;


public class FinestraOpzioni {
    private JPanel panelOpzioni;
    private JButton creaUnaPaginaButton;
    private JButton cercaUnaPaginaButton;
    private JButton proponiUnaModificaButton;
    private JButton valutaUnaModificaButton;
    private JPanel panelCreaPagina;
    private JPanel panelCercaPagina;
    private JPanel panelProponiModifica;
    private JPanel panelValutaModifica;
    private JButton annullaButton;
    private JPanel panelAnnulla;
    private static JFrame frame;
    private Controller controller;
    private static JFrame frameChiamante;
    private Utente u;
    private String identita;

    public FinestraOpzioni(JFrame frameChiamante, Controller controller, Utente u, String identita) {
        this.u = u;
        this.identita = identita;
        this.frameChiamante = frameChiamante;
        this.controller = controller;
        frame = new JFrame("Area Opzioni");
        frame.setContentPane(panelOpzioni);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frameChiamante.setVisible(false);
        frame.setVisible(true);

        if (identita.equals("UTENTE")) {
            creaUnaPaginaButton.setEnabled(false);
            valutaUnaModificaButton.setEnabled(false);
        }

        if (!(controller.esisteAlmenoUnaPagina())) {
            cercaUnaPaginaButton.setEnabled(false);
            proponiUnaModificaButton.setEnabled(false);
            valutaUnaModificaButton.setEnabled(false);
        }
        creaUnaPaginaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String titolo = JOptionPane.showInputDialog("Inserisci il titolo della pagina");
                Date now = controller.getCurrentDateTime();
                controller.setPagina(titolo, now, (Autore) u);
                // crea in controller set testo
                JOptionPane.showMessageDialog(frame, "Ciao " + u.getUsername() + " hai creato una pagina");
                cercaUnaPaginaButton.setEnabled(true);
                proponiUnaModificaButton.setEnabled(true);
                valutaUnaModificaButton.setEnabled(true);
            }
        });
        cercaUnaPaginaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        proponiUnaModificaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        valutaUnaModificaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        annullaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frameChiamante.setVisible(true);
                frame.setVisible(false);
                frame.dispose();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelOpzioni = new JPanel();
        panelOpzioni.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelCreaPagina = new JPanel();
        panelCreaPagina.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelOpzioni.add(panelCreaPagina);
        creaUnaPaginaButton = new JButton();
        creaUnaPaginaButton.setText("Crea Una Pagina");
        panelCreaPagina.add(creaUnaPaginaButton);
        panelCercaPagina = new JPanel();
        panelCercaPagina.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelOpzioni.add(panelCercaPagina);
        cercaUnaPaginaButton = new JButton();
        cercaUnaPaginaButton.setText("Cerca Una Pagina");
        panelCercaPagina.add(cercaUnaPaginaButton);
        panelProponiModifica = new JPanel();
        panelProponiModifica.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelOpzioni.add(panelProponiModifica);
        proponiUnaModificaButton = new JButton();
        proponiUnaModificaButton.setText("Proponi Una Modifica");
        panelProponiModifica.add(proponiUnaModificaButton);
        panelValutaModifica = new JPanel();
        panelValutaModifica.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelOpzioni.add(panelValutaModifica);
        valutaUnaModificaButton = new JButton();
        valutaUnaModificaButton.setText("Valuta Una Modifica");
        panelValutaModifica.add(valutaUnaModificaButton);
        panelAnnulla = new JPanel();
        panelAnnulla.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelOpzioni.add(panelAnnulla);
        annullaButton = new JButton();
        annullaButton.setText("Torna All'Area Login");
        panelAnnulla.add(annullaButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelOpzioni;
    }

}