package gui;

import controller.*;
import model.Utente;
import postgresDAO.ListinoPostgresDAO;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;

public class Home {
    private JPanel panelHome;
    private JButton registrazioneUtenteButton;
    private JButton inserisciAutoreButton;
    private JButton loginButton;
    private JPanel panelRegistrazioneUtente;
    private JPanel panelLogin;
    private JPanel panelUsername;
    private JPanel panelPassword;
    private JTextField usernameTextField;
    private JPasswordField passwordField;
    private static JFrame frame;
    private Controller controller = new Controller(new ListinoPostgresDAO());
    private String usernameInserito;
    private String passwordInserita;

    public Home() {
        controller.setSchema();
        if(controller.almenoUnAutoreOUnUtente()) {
            loginButton.setEnabled(true);
        } else {
            loginButton.setEnabled(false);
        }

        usernameTextField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        passwordField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        registrazioneUtenteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                usernameInserito = usernameTextField.getText();
                char[] passwordChars = passwordField.getPassword();  // per ottenere la password
                passwordInserita = new String(passwordChars);
                try {
                    controller.setUtente(usernameInserito, passwordInserita);
                    JOptionPane.showMessageDialog(frame, "Ciao " + usernameInserito + " benvenuto nel nostro sistema");
                } catch (invalidLoginException il) {
                    JOptionPane.showMessageDialog(frame, "Non puoi lasciare un campo vuoto.");
                } catch (GiaEsistenteException ex) {
                    JOptionPane.showMessageDialog(frame, "L'username inserito è già esistente");
                } catch (LunghezzaMinimaException ex) {
                    JOptionPane.showMessageDialog(frame, "La password deve essere lunga almeno 6 caratteri");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(frame, "Errore generico");
                }
                if(controller.almenoUnAutoreOUnUtente()) {
                    loginButton.setEnabled(true);
                } else {
                    loginButton.setEnabled(false);
                }
            }
        });
        loginButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                usernameInserito = usernameTextField.getText();
                char[] passwordChars = passwordField.getPassword();  // per ottenere la password
                passwordInserita = new String(passwordChars);
                String returnLogin = null;
                try {
                    controller.login(usernameInserito, passwordInserita);
                    JOptionPane.showMessageDialog(frame, "Ciao " + usernameInserito);
                    Utente u = controller.getUtente(usernameInserito);
                    FinestraOpzioni finestraOpzioni = new FinestraOpzioni(frame, controller, u);
                    frame.setVisible(false);
                    frame.dispose();
                } catch (invalidLoginException il) {
                    JOptionPane.showMessageDialog(frame, "Non puoi lasciare un campo vuoto.");
                } catch (usernameNotFoundException unf) {
                    JOptionPane.showMessageDialog(frame, "Username non esistente.");
                } catch (passwordNotFoundException pnf) {
                    JOptionPane.showMessageDialog(frame, "Password errata.");
                }
            }
        });
        panelHome.addComponentListener(new ComponentAdapter() {
        });
    }

    public static void main(String[] args) {
        frame = new JFrame("Progetto OO");
        Home home = new Home();
        frame.setContentPane(new Home().panelHome);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelHome = new JPanel();
        panelHome.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelHome.setPreferredSize(new Dimension(500, 300));
        panelRegistrazioneUtente = new JPanel();
        panelRegistrazioneUtente.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelHome.add(panelRegistrazioneUtente);
        registrazioneUtenteButton = new JButton();
        registrazioneUtenteButton.setMinimumSize(new Dimension(128, 30));
        registrazioneUtenteButton.setPreferredSize(new Dimension(128, 30));
        registrazioneUtenteButton.setText("Inserisci Utente");
        panelRegistrazioneUtente.add(registrazioneUtenteButton);
        inserisciAutoreButton = new JButton();
        inserisciAutoreButton.setText("Inserisci Autore");
        panelLogin = new JPanel();
        panelLogin.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelHome.add(panelLogin);
        loginButton = new JButton();
        loginButton.setText("Login");
        panelLogin.add(loginButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelHome;
    }

}
