package gui;

import controller.Controller;
import postgresDAO.ListinoPostgresDAO;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;

public class Home {
    private JPanel panelHome;
    private JButton inserisciUtenteButton;
    private JButton inserisciAutoreButton;
    private JButton loginButton;
    private JPanel panelRegistrazioneUtente;
    private JPanel panelRegistrazioneAutore;
    private JPanel panelLogin;
    private static JFrame frame;
    private Controller controller = new Controller(new ListinoPostgresDAO());

    public Home() {
        controller.setSchema();
        if(controller.almenoUnAutoreOUnUtente()) {
            loginButton.setEnabled(true);
        } else {
            loginButton.setEnabled(false);
        }
        inserisciUtenteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                FinestraInserisciUtente inserisciUtente = new FinestraInserisciUtente(frame, controller);
                loginButton.setEnabled(true);
            }
        });
        inserisciAutoreButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                loginButton.setEnabled(true);
            }
        });
        loginButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Login login = new Login(frame, controller);
            }
        });
        panelHome.addComponentListener(new ComponentAdapter() {
        });
    }

    public static void main(String[] args) {
        frame = new JFrame("Progetto OO");
        Home home = new Home();
        frame.setContentPane(new Home().panelHome);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelHome = new JPanel();
        panelHome.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelHome.setPreferredSize(new Dimension(500, 300));
        panelRegistrazioneUtente = new JPanel();
        panelRegistrazioneUtente.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelHome.add(panelRegistrazioneUtente);
        inserisciUtenteButton = new JButton();
        inserisciUtenteButton.setMinimumSize(new Dimension(128, 30));
        inserisciUtenteButton.setPreferredSize(new Dimension(128, 30));
        inserisciUtenteButton.setText("Inserisci Utente");
        panelRegistrazioneUtente.add(inserisciUtenteButton);
        panelRegistrazioneAutore = new JPanel();
        panelRegistrazioneAutore.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelHome.add(panelRegistrazioneAutore);
        inserisciAutoreButton = new JButton();
        inserisciAutoreButton.setText("Inserisci Autore");
        panelRegistrazioneAutore.add(inserisciAutoreButton);
        panelLogin = new JPanel();
        panelLogin.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelHome.add(panelLogin);
        loginButton = new JButton();
        loginButton.setText("Login");
        panelLogin.add(loginButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelHome;
    }

}
