package gui;

import controller.Controller;
import model.invalidLoginException;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Login {
    private JPanel panelLogin;
    private JPanel panelUsername;
    private JTextField usernameTextField;
    private JPasswordField passwordField;
    private JButton inviaCredenzialiButton;
    private JPanel panelPassword;
    private JPanel panelBotton;
    private static JFrame frame;
    private Controller controller;
    private static JFrame frameChiamante;
    private String usernameInserito;
    private String passwordInserita;

    public Login(JFrame frameChiamante, Controller controller) {
        this.frameChiamante = frameChiamante;
        this.controller = controller;
        frame = new JFrame("Registrazione Utente");
        frame.setContentPane(panelLogin);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        usernameTextField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            }
        });
        passwordField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        inviaCredenzialiButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                usernameInserito = usernameTextField.getText();
                char[] passwordChars = passwordField.getPassword();  // per ottenere la password
                passwordInserita = new String(passwordChars);
                String returnLogin = "";
                try {
                    if (!(usernameInserito.isEmpty() || passwordInserita.isEmpty())) {
                        returnLogin = controller.login(usernameInserito, passwordInserita);
                    }
                } catch (invalidLoginException il) {
                    throw new RuntimeException(il);
                }
                JOptionPane.showMessageDialog(frame, "Ciao " + usernameInserito + " sei un " + returnLogin);
                frameChiamante.setVisible(true);
                frame.setVisible(false);
                frame.dispose();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelLogin = new JPanel();
        panelLogin.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelLogin.setPreferredSize(new Dimension(49, 30));
        panelLogin.setVisible(true);
        panelUsername = new JPanel();
        panelUsername.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelUsername.setPreferredSize(new Dimension(88, 40));
        panelLogin.add(panelUsername);
        usernameTextField = new JTextField();
        usernameTextField.setPreferredSize(new Dimension(78, 30));
        usernameTextField.setToolTipText("");
        panelUsername.add(usernameTextField);
        panelPassword = new JPanel();
        panelPassword.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelPassword.setPreferredSize(new Dimension(88, 40));
        panelLogin.add(panelPassword);
        passwordField = new JPasswordField();
        passwordField.setPreferredSize(new Dimension(78, 30));
        passwordField.setToolTipText("");
        panelPassword.add(passwordField);
        panelBotton = new JPanel();
        panelBotton.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelLogin.add(panelBotton);
        inviaCredenzialiButton = new JButton();
        inviaCredenzialiButton.setText("Login");
        panelBotton.add(inviaCredenzialiButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelLogin;
    }

}
